sudo: false
language: node_js
node_js: "node"
os: linux
env: ELM_VERSION=rc1

cache:
  directories:
    - test/elm-stuff/build-artifacts
    - sysconfcpus

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - | # epic build time improvement - see https://github.com/elm-lang/elm-compiler/issues/1473#issuecomment-245704142
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi

install:
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION
  - mv $(npm config get prefix)/bin/elm $(npm config get prefix)/bin/elm-old
  - printf '%s\n\n' '#!/bin/bash' 'echo "Running elm with sysconfcpus -n 2"' '$TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-old "$@"' > $(npm config get prefix)/bin/elm
  - chmod +x $(npm config get prefix)/bin/elm
  - npm install

script:
  - npm run ci
